[project]
name = "intro-aiml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
     "pandas",
    "numpy",
    "scikit-learn",
    "statsmodels",
    "matplotlib",
    "seaborn"
]
